### ISSUE TITLE
possibility to assign 2 types to 1 snippet?

### ISSUE THREAD

**Issue by mackelito** [thibmaek/modular-snippets#1]
I'm looking for the possibility to have a snippet in 2 filetypes

java and html.. is that possible?

Something like:
```
   '.source.java', 'text.html.basic':
      'Spring Theme':
        'prefix': 'spring'
        'body': '<spring:theme code"$1translation string'
```

**Comment by thibmaek** [comment]
I don't know if that is possible but I suggest looking into the official repo for this: https://github.com/atom/snippets

I rather think it won't be possible and would kinda defeat the purpose of this repo (keeping it modular across languages). Will put this issue on hold for now, thanks.

**Comment by thibmaek** [comment]
I did some research and it seems that while it would be possible to do this if you could target file extensions, you can't in Atom's current version. The snippets work on the scope they're defined for and only 1 scope is available per language package.

Nevertheless, this might we worth opening an issue or PR for on the snippets repo, thanks bringing it to my attention anyway :clap:
